project_id = "ailuplgwqkregigmufsj"

[functions.extract-skills]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.evaluate-answer]
verify_jwt = false

[functions.generate-report]
verify_jwt = false
